In [2]:
import os
import pandas as pd
import numpy as np
import random
import dendropy
import treeswift
from treeswift import read_tree_newick
#import matplotlib.pyplot as plt
import re

In [3]:
print(os.getcwd())

/Users/nora/Documents/ml_metagenomics/tol_variable_k_resuls/revisions_AMBER

In [4]:
classes_p = "/Users/nora/Documents/ml_metagenomics/tol_variable_k_resuls/cami_gsa_pooled/cami_short_reads_gsa_pooled_5kfilt_contigs"
classes_f = "cami_gsa_short_reads_all_classes_w_header.out"
classes_df = pd.read_csv(os.path.join(classes_p, classes_f), sep = "\t", header = 0)

In [5]:
#classes_df = classes_df.loc[:, classes_df.columns.intersection(['genome','top_class'])]

In [6]:
classes_df.rename(columns=lambda x: 'clade_' + x if x not in ['genome','top_class', 'top_p'] else x, inplace=True)

In [7]:
classes_df

,genome,top_class,top_p,clade_0,clade_1,clade_2,clade_3,clade_4,clade_5,clade_6,clade_7,clade_8,clade_9,clade_10,clade_11,clade_12,clade_13,clade_14,clade_15
0,PC96897,13.0,1.000000,2.828151e-23,1.300274e-27,1.909033e-26,2.160892e-19,2.009723e-32,1.816115e-13,4.087004e-26,8.811919e-38,1.493710e-33,4.056344e-26,4.550718e-31,2.262148e-22,1.604813e-22,1.000000e+00,8.868323e-11,2.914108e-17
1,PC988428,10.0,1.000000,3.696906e-41,4.672891e-24,1.703767e-28,6.741611e-29,1.057825e-27,3.044746e-32,4.802668e-23,1.804618e-27,2.855223e-20,4.020191e-10,1.000000e+00,1.172057e-30,9.781976e-13,5.631452e-29,5.747313e-32,1.130842e-30
2,PC988212,10.0,1.000000,0.000000e+00,1.509885e-40,0.000000e+00,0.000000e+00,1.401298e-45,6.566050e-37,1.321604e-39,6.317558e-33,5.336821e-28,3.939272e-20,1.000000e+00,4.063766e-43,5.534757e-31,4.820467e-43,4.623470e-33,3.719028e-28
3,PC976607,4.0,1.000000,8.856206e-43,1.994640e-38,1.473306e-36,6.351124e-32,1.000000e+00,1.537777e-19,1.128529e-29,1.587588e-36,0.000000e+00,0.000000e+00,1.853918e-41,6.295699e-30,3.889430e-27,5.197344e-22,8.324072e-31,5.554951e-18
4,PC956737,13.0,1.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.401298e-45,0.000000e+00,7.496947e-43,0.000000e+00,0.000000e+00,2.844242e-28,7.006492e-45,1.297982e-37,2.371796e-30,1.000000e+00,4.447918e-36,4.883634e-34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51235,PC835777,3.0,0.999999,2.651828e-32,1.700928e-22,1.429786e-06,9.999986e-01,3.464907e-14,7.073279e-14,2.112509e-28,2.075957e-24,4.016617e-26,8.216898e-24,5.439570e-28,4.213335e-24,1.177180e-19,7.559950e-24,4.465035e-11,5.362542e-18
51236,PC866532,13.0,1.000000,4.804060e-16,6.967587e-15,4.165061e-23,1.023033e-12,1.776413e-23,8.070257e-28,1.825344e-22,7.474186e-23,4.268673e-27,6.385947e-29,9.308955e-21,6.205846e-17,1.513823e-16,1.000000e+00,1.125005e-12,9.447890e-17
51237,PC843714,13.0,0.999929,1.506772e-22,1.173792e-23,6.527935e-12,6.416671e-20,9.273941e-20,3.571406e-14,8.598757e-25,2.233757e-36,2.835350e-27,1.355234e-22,1.616703e-22,1.615021e-21,6.620195e-12,9.999292e-01,7.076684e-05,7.102196e-10
51238,PC863748,10.0,0.991869,1.387357e-30,2.260021e-12,2.470852e-24,1.282304e-20,2.666388e-14,3.668712e-12,1.422128e-14,9.214268e-14,5.771563e-03,7.979909e-08,9.918694e-01,7.314752e-11,1.909965e-03,1.063365e-17,4.467255e-04,2.221987e-06
51239,PC897370,11.0,1.000000,6.594735e-40,1.808196e-32,1.851686e-30,1.052898e-33,9.733682e-16,3.568218e-11,8.961638e-19,3.696358e-19,6.036976e-26,1.440427e-09,2.631495e-30,1.000000e+00,1.384077e-10,1.694507e-18,2.858654e-14,1.608632e-14

In [10]:
original_classes = classes_df.iloc[:, :3]

In [11]:
original_classes

         genome  top_class     top_p
0       PC96897       13.0  1.000000
1      PC988428       10.0  1.000000
2      PC988212       10.0  1.000000
3      PC976607        4.0  1.000000
4      PC956737       13.0  1.000000
...         ...        ...       ...
51235  PC835777        3.0  0.999999
51236  PC866532       13.0  1.000000
51237  PC843714       13.0  0.999929
51238  PC863748       10.0  0.991869
51239  PC897370       11.0  1.000000

[51240 rows x 3 columns]

In [14]:
classes_p = "/Users/nora/Documents/ml_metagenomics/tol_variable_k_resuls/revisions_AMBER"
classes_f = "classes.out"
classes_df = pd.read_csv(os.path.join(classes_p, classes_f), sep = "\t", header = 0)

In [15]:
new_classes = classes_df.iloc[:, :3]

In [16]:
new_classes

          genome  top_class     top_p
0      PC1267800         10  1.000000
1        PC81258         10  1.000000
2       PC733121         13  0.851993
3       PC420514          6  1.000000
4       PC237485          3  0.985108
...          ...        ...       ...
20287  PC1043881         10  1.000000
20288   PC324296         14  1.000000
20289   PC453227         10  1.000000
20290  PC1208548          9  1.000000
20291   PC920878         11  1.000000

[20292 rows x 3 columns]

In [17]:
combo = pd.merge(original_classes, new_classes, how = 'right', left_on = "genome", right_on = "genome")

In [18]:
combo

          genome  top_class_x   top_p_x  top_class_y   top_p_y
0      PC1267800         10.0  1.000000           10  1.000000
1        PC81258         10.0  1.000000           10  1.000000
2       PC733121         13.0  0.851992           13  0.851993
3       PC420514          6.0  1.000000            6  1.000000
4       PC237485          3.0  0.985108            3  0.985108
...          ...          ...       ...          ...       ...
20287  PC1043881         10.0  1.000000           10  1.000000
20288   PC324296         14.0  1.000000           14  1.000000
20289   PC453227         10.0  1.000000           10  1.000000
20290  PC1208548          9.0  1.000000            9  1.000000
20291   PC920878         11.0  1.000000           11  1.000000

[20292 rows x 5 columns]

In [21]:
df_diff = combo[combo['top_class_x'] == combo['top_class_y']]

In [22]:
len(df_diff)

20292

In [53]:
# Read contig to parent genome map

map_path = "/Users/nora/Documents/ml_metagenomics/cami_short_reads"
my_map_df = pd.read_csv (os.path.join(map_path, "short_gsa_mapped_to_parental_genomes.tsv"), sep = "\t", header = 0)

In [54]:
my_map_df.columns

Index(['label', '#anonymous_contig_id', 'genome_id', 'tax_id', 'contig_id',
       'number_reads', 'start_position', 'end_position', 'otu', 'full_path',
       'path', 'new_label'],
      dtype='object')

In [55]:
classes_df_prelim = pd.merge (classes_df, my_map_df, how = "inner", left_on = "genome", right_on = "label")

In [56]:
classes_df_prelim.head (n=5)

,genome,top_class,top_p,clade_0,clade_1,clade_2,clade_3,clade_4,clade_5,clade_6,...,genome_id,tax_id,contig_id,number_reads,start_position,end_position,otu,full_path,path,new_label
0,PC96897,13.0,1.0,2.828151e-23,1.300274e-27,1.909033e-26,2.160892e-19,2.009723e-32,1.816115e-13,4.087004e-26,...,Otu1168.0,1453352,CP010535.1,214,1326961,1332977,Otu1168.0,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Sediminicola_sp_YIK13_genomic.kf,Sediminicola_sp_YIK13_genomic
1,PC988428,10.0,1.0,3.696906e-41,4.672891e-24,1.703767e-28,6.741611e-29,1.057825e-27,3.044746e-32,4.802668e-23,...,Otu1132,80852,NODE_76_length_18850_cov_92.515569,276,8186,16309,Otu1132,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,VwK7F1_S12_contigs.kf,VwK7F1_S12_contigs
2,PC988212,10.0,1.0,0.000000e+00,1.509885e-40,0.000000e+00,0.000000e+00,1.401298e-45,6.566050e-37,1.321604e-39,...,Otu1225,62322,NODE_39_length_27622_cov_43.324168,635,13834,27609,Otu1225,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,MC4_S2_contigs.kf,MC4_S2_contigs
3,PC976607,4.0,1.0,8.856206e-43,1.994640e-38,1.473306e-36,6.351124e-32,1.000000e+00,1.537777e-19,1.128529e-29,...,Otu812,1760,NODE_4_length_310521_cov_112.470128,236,85326,93472,Otu812,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Titti28_S8_contigs.kf,Titti28_S8_contigs
4,PC956737,13.0,1.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.401298e-45,0.000000e+00,7.496947e-43,...,Otu612.0,979,CP002534.1,276,1299315,1308746,Otu612.0,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Cellulophaga_lytica_DSM_7489_genomic.kf,Cellulophaga_lytica_DSM_7489_genomic

In [57]:
classes_df_prelim.columns

Index(['genome', 'top_class', 'top_p', 'clade_0', 'clade_1', 'clade_2',
       'clade_3', 'clade_4', 'clade_5', 'clade_6', 'clade_7', 'clade_8',
       'clade_9', 'clade_10', 'clade_11', 'clade_12', 'clade_13', 'clade_14',
       'clade_15', 'label', '#anonymous_contig_id', 'genome_id', 'tax_id',
       'contig_id', 'number_reads', 'start_position', 'end_position', 'otu',
       'full_path', 'path', 'new_label'],
      dtype='object')

In [58]:
# classes_df["tmp"] =  classes_df["genome"]
# classes_df[['parent_genome', 'suffix']] = classes_df['tmp'].str.split('.', n=1, expand=True)

In [59]:
# classes_df.drop(columns = ["tmp", "suffix"], inplace = True)

In [60]:
my_path = "/Users/nora/Documents/ml_metagenomics/tol_variable_k_resuls/cami_gsa_pooled"

true_clades = pd.read_csv(os.path.join(my_path, "cami_full_genomes_classes.out"), sep = "\t", header = 0)

In [61]:
true_clades = true_clades.loc[:, classes_df.columns.intersection(['genome','top_class'])]

In [62]:
true_clades

                                  genome  top_class
0    RNODE_407_length_46658_cov_49.66972       11.0
1      RNODE_470_length_2095_cov_7.42232        4.0
2      Arthrobacter_sp_PAMC25486_genomic        4.0
3                         S13_S3_contigs        3.0
4     Methanotorris_igneus_Kol_5_genomic       15.0
..                                   ...        ...
972    RNODE_531_length_9868_cov_8.44904       11.0
973        Sulfurovum_sp_NBC37-1_genomic       15.0
974    Flavobacterium_sp_LPB0076_genomic       13.0
975                       12_S12_contigs       10.0
976          Mesorhizobium_sp_B7_genomic       11.0

[977 rows x 2 columns]

In [63]:
classes_df_merged = pd.merge(classes_df_prelim, true_clades, how = "left", left_on = "new_label", right_on = "genome")

In [64]:
classes_df_merged

,genome_x,top_class_x,top_p,clade_0,clade_1,clade_2,clade_3,clade_4,clade_5,clade_6,...,contig_id,number_reads,start_position,end_position,otu,full_path,path,new_label,genome_y,top_class_y
0,PC96897,13.0,1.000000,2.828151e-23,1.300274e-27,1.909033e-26,2.160892e-19,2.009723e-32,1.816115e-13,4.087004e-26,...,CP010535.1,214,1326961,1332977,Otu1168.0,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Sediminicola_sp_YIK13_genomic.kf,Sediminicola_sp_YIK13_genomic,Sediminicola_sp_YIK13_genomic,13.0
1,PC988428,10.0,1.000000,3.696906e-41,4.672891e-24,1.703767e-28,6.741611e-29,1.057825e-27,3.044746e-32,4.802668e-23,...,NODE_76_length_18850_cov_92.515569,276,8186,16309,Otu1132,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,VwK7F1_S12_contigs.kf,VwK7F1_S12_contigs,VwK7F1_S12_contigs,10.0
2,PC988212,10.0,1.000000,0.000000e+00,1.509885e-40,0.000000e+00,0.000000e+00,1.401298e-45,6.566050e-37,1.321604e-39,...,NODE_39_length_27622_cov_43.324168,635,13834,27609,Otu1225,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,MC4_S2_contigs.kf,MC4_S2_contigs,MC4_S2_contigs,10.0
3,PC976607,4.0,1.000000,8.856206e-43,1.994640e-38,1.473306e-36,6.351124e-32,1.000000e+00,1.537777e-19,1.128529e-29,...,NODE_4_length_310521_cov_112.470128,236,85326,93472,Otu812,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Titti28_S8_contigs.kf,Titti28_S8_contigs,Titti28_S8_contigs,4.0
4,PC956737,13.0,1.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.401298e-45,0.000000e+00,7.496947e-43,...,CP002534.1,276,1299315,1308746,Otu612.0,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Cellulophaga_lytica_DSM_7489_genomic.kf,Cellulophaga_lytica_DSM_7489_genomic,Cellulophaga_lytica_DSM_7489_genomic,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51235,PC835777,3.0,0.999999,2.651828e-32,1.700928e-22,1.429786e-06,9.999986e-01,3.464907e-14,7.073279e-14,2.112509e-28,...,NZ_CP017770.1,402,3085501,3095245,Otu722,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Paenibacillus_sp_LPB0068_genomic.kf,Paenibacillus_sp_LPB0068_genomic,Paenibacillus_sp_LPB0068_genomic,3.0
51236,PC866532,13.0,1.000000,4.804060e-16,6.967587e-15,4.165061e-23,1.023033e-12,1.776413e-23,8.070257e-28,1.825344e-22,...,NODE_14_length_85852_cov_79.949699,1702,54953,85835,Otu491.0,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,26_S2_contigs.kf,26_S2_contigs,26_S2_contigs,13.0
51237,PC843714,13.0,0.999929,1.506772e-22,1.173792e-23,6.527935e-12,6.416671e-20,9.273941e-20,3.571406e-14,8.598757e-25,...,CP002157.1,218,3718871,3726221,Otu1267.0,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Maribacter_sp_HTCC2170_genomic.kf,Maribacter_sp_HTCC2170_genomic,Maribacter_sp_HTCC2170_genomic,13.0
51238,PC863748,10.0,0.991869,1.387357e-30,2.260021e-12,2.470852e-24,1.282304e-20,2.666388e-14,3.668712e-12,1.422128e-14,...,CP000444.1,264,2647833,2657745,Otu2333,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Shewanella_sp_MR-7_genomic.kf,Shewanella_sp_MR-7_genomic,Shewanella_sp_MR-7_genomic,10.0
51239,PC897370,11.0,1.000000,6.594735e-40,1.808196e-32,1.851686e-30,1.052898e-33,9.733682e-16,3.568218e-11,8.961638e-19,...,0RNODE_248_length_5318_cov_4.74604,776,13,5294,RNODE_248_length_5318_cov_4.74604,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,RNODE_248_length_5318_cov_4.74604.kf,RNODE_248_length_5318_cov_4.74604,RNODE_248_length_5318_cov_4.74604,11.0

In [65]:
classes_df_merged.drop(columns = ["genome_y"], inplace = True)

In [66]:
classes_df_merged.rename(columns = {"top_class_y":"true_clade"}, inplace = True)

In [67]:
classes_df_merged.rename(columns = {"top_class_x":"top_class"}, inplace = True)
#classes_df_merged.rename(columns = {"genome_x":"genome"}, inplace = True)

In [68]:
classes_df_merged

,genome_x,top_class,top_p,clade_0,clade_1,clade_2,clade_3,clade_4,clade_5,clade_6,...,tax_id,contig_id,number_reads,start_position,end_position,otu,full_path,path,new_label,true_clade
0,PC96897,13.0,1.000000,2.828151e-23,1.300274e-27,1.909033e-26,2.160892e-19,2.009723e-32,1.816115e-13,4.087004e-26,...,1453352,CP010535.1,214,1326961,1332977,Otu1168.0,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Sediminicola_sp_YIK13_genomic.kf,Sediminicola_sp_YIK13_genomic,13.0
1,PC988428,10.0,1.000000,3.696906e-41,4.672891e-24,1.703767e-28,6.741611e-29,1.057825e-27,3.044746e-32,4.802668e-23,...,80852,NODE_76_length_18850_cov_92.515569,276,8186,16309,Otu1132,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,VwK7F1_S12_contigs.kf,VwK7F1_S12_contigs,10.0
2,PC988212,10.0,1.000000,0.000000e+00,1.509885e-40,0.000000e+00,0.000000e+00,1.401298e-45,6.566050e-37,1.321604e-39,...,62322,NODE_39_length_27622_cov_43.324168,635,13834,27609,Otu1225,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,MC4_S2_contigs.kf,MC4_S2_contigs,10.0
3,PC976607,4.0,1.000000,8.856206e-43,1.994640e-38,1.473306e-36,6.351124e-32,1.000000e+00,1.537777e-19,1.128529e-29,...,1760,NODE_4_length_310521_cov_112.470128,236,85326,93472,Otu812,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Titti28_S8_contigs.kf,Titti28_S8_contigs,4.0
4,PC956737,13.0,1.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.401298e-45,0.000000e+00,7.496947e-43,...,979,CP002534.1,276,1299315,1308746,Otu612.0,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Cellulophaga_lytica_DSM_7489_genomic.kf,Cellulophaga_lytica_DSM_7489_genomic,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51235,PC835777,3.0,0.999999,2.651828e-32,1.700928e-22,1.429786e-06,9.999986e-01,3.464907e-14,7.073279e-14,2.112509e-28,...,1763538,NZ_CP017770.1,402,3085501,3095245,Otu722,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Paenibacillus_sp_LPB0068_genomic.kf,Paenibacillus_sp_LPB0068_genomic,3.0
51236,PC866532,13.0,1.000000,4.804060e-16,6.967587e-15,4.165061e-23,1.023033e-12,1.776413e-23,8.070257e-28,1.825344e-22,...,237,NODE_14_length_85852_cov_79.949699,1702,54953,85835,Otu491.0,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,26_S2_contigs.kf,26_S2_contigs,13.0
51237,PC843714,13.0,0.999929,1.506772e-22,1.173792e-23,6.527935e-12,6.416671e-20,9.273941e-20,3.571406e-14,8.598757e-25,...,313603,CP002157.1,218,3718871,3726221,Otu1267.0,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Maribacter_sp_HTCC2170_genomic.kf,Maribacter_sp_HTCC2170_genomic,13.0
51238,PC863748,10.0,0.991869,1.387357e-30,2.260021e-12,2.470852e-24,1.282304e-20,2.666388e-14,3.668712e-12,1.422128e-14,...,22,CP000444.1,264,2647833,2657745,Otu2333,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Shewanella_sp_MR-7_genomic.kf,Shewanella_sp_MR-7_genomic,10.0
51239,PC897370,11.0,1.000000,6.594735e-40,1.808196e-32,1.851686e-30,1.052898e-33,9.733682e-16,3.568218e-11,8.961638e-19,...,32644,0RNODE_248_length_5318_cov_4.74604,776,13,5294,RNODE_248_length_5318_cov_4.74604,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,RNODE_248_length_5318_cov_4.74604.kf,RNODE_248_length_5318_cov_4.74604,11.0

In [69]:
classes_df_merged['top_class'] = classes_df_merged['top_class'].astype('int')
classes_df_merged['true_clade'] = classes_df_merged['true_clade'].astype('int')

In [70]:
len(classes_df_merged)
classes_df_merged.head(n=5)

,genome_x,top_class,top_p,clade_0,clade_1,clade_2,clade_3,clade_4,clade_5,clade_6,...,tax_id,contig_id,number_reads,start_position,end_position,otu,full_path,path,new_label,true_clade
0,PC96897,13,1.0,2.828151e-23,1.300274e-27,1.909033e-26,2.160892e-19,2.009723e-32,1.816115e-13,4.087004e-26,...,1453352,CP010535.1,214,1326961,1332977,Otu1168.0,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Sediminicola_sp_YIK13_genomic.kf,Sediminicola_sp_YIK13_genomic,13
1,PC988428,10,1.0,3.696906e-41,4.672891e-24,1.703767e-28,6.741611e-29,1.057825e-27,3.044746e-32,4.802668e-23,...,80852,NODE_76_length_18850_cov_92.515569,276,8186,16309,Otu1132,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,VwK7F1_S12_contigs.kf,VwK7F1_S12_contigs,10
2,PC988212,10,1.0,0.000000e+00,1.509885e-40,0.000000e+00,0.000000e+00,1.401298e-45,6.566050e-37,1.321604e-39,...,62322,NODE_39_length_27622_cov_43.324168,635,13834,27609,Otu1225,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,MC4_S2_contigs.kf,MC4_S2_contigs,10
3,PC976607,4,1.0,8.856206e-43,1.994640e-38,1.473306e-36,6.351124e-32,1.000000e+00,1.537777e-19,1.128529e-29,...,1760,NODE_4_length_310521_cov_112.470128,236,85326,93472,Otu812,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Titti28_S8_contigs.kf,Titti28_S8_contigs,4
4,PC956737,13,1.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.401298e-45,0.000000e+00,7.496947e-43,...,979,CP002534.1,276,1299315,1308746,Otu612.0,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Cellulophaga_lytica_DSM_7489_genomic.kf,Cellulophaga_lytica_DSM_7489_genomic,13

In [71]:
my_subset = classes_df_merged.loc[~(classes_df_merged['top_class'] == classes_df_merged['true_clade'])]

In [72]:
my_subset

,genome_x,top_class,top_p,clade_0,clade_1,clade_2,clade_3,clade_4,clade_5,clade_6,...,tax_id,contig_id,number_reads,start_position,end_position,otu,full_path,path,new_label,true_clade
16,PC965849,5,1.000000,2.115612e-37,9.570280e-40,1.015157e-34,2.191820e-31,1.357953e-08,1.000000e+00,8.193625e-28,...,1760,NODE_6_length_217206_cov_30.508446,147,153250,158830,Otu2206,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,AW19M33_S12_contigs.kf,AW19M33_S12_contigs,4
35,PC972663,9,0.742206,1.037522e-37,4.240434e-27,1.010457e-12,3.896752e-19,7.387423e-11,5.329859e-22,8.604076e-13,...,1238,NZ_CP013801.1,160,2229994,2236126,Otu1101.0,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Piscirickettsia_salmonis_strain_PM22180B_genom...,Piscirickettsia_salmonis_strain_PM22180B_genomic,12
59,PC962793,0,0.958185,9.581850e-01,6.012787e-04,1.328956e-15,4.784221e-05,1.045041e-11,1.303538e-13,5.220740e-08,...,99286,NODE_5_length_331421_cov_210.910267,179,180026,185623,Otu429.0,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,R2A2_S5_contigs.kf,R2A2_S5_contigs,13
99,PC974520,12,0.999978,1.339726e-23,2.282900e-16,1.479390e-20,3.114566e-14,3.842391e-10,1.238935e-07,2.143467e-05,...,106589,NZ_CP017754.1,628,1296514,1313854,Otu1279,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Cupriavidus_sp_USMAA1020_genomic.kf,Cupriavidus_sp_USMAA1020_genomic,6
111,PC953214,4,0.987302,5.721464e-37,1.605452e-27,5.747933e-30,1.231114e-31,9.873016e-01,1.269505e-02,5.420907e-20,...,1705,NZ_CP009251.1,118,2253006,2258453,Otu2174,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Corynebacterium_stationis_strain_622_DSM_20302...,Corynebacterium_stationis_strain_622_DSM_20302...,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51063,PC811882,9,0.663707,2.753301e-18,1.795163e-08,5.163334e-15,8.397612e-14,6.636131e-10,4.328111e-20,1.083488e-14,...,190893,NZ_CP016556.1,194,2990164,2996027,Otu1010,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Vibrio_coralliilyticus_strain_58_genomic.kf,Vibrio_coralliilyticus_strain_58_genomic,10
51110,PC801820,7,1.000000,1.401298e-45,2.842410e-20,6.376684e-33,2.433341e-11,3.880827e-23,7.837634e-30,1.126796e-35,...,40269,NODE_61_length_6215_cov_100.552398,226,1,6173,Otu395,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,A-Hdes-11_S10_contigs.kf,A-Hdes-11_S10_contigs,10
51118,PC905533,8,0.571903,7.127340e-33,3.538259e-09,1.343061e-13,3.022602e-04,7.049106e-21,7.207122e-25,1.281184e-21,...,80854,NODE_5_length_237324_cov_100.486743,194,50747,56297,Otu766,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,MvHd14_S5_contigs.kf,MvHd14_S5_contigs,10
51217,PC816555,9,0.993856,5.962201e-35,4.233066e-26,3.592584e-26,8.486795e-23,7.164721e-16,7.465212e-15,5.086604e-10,...,1248727,AP012978.1,701,1201663,1215280,Otu1126,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,endosymbiont_of_unidentified_scaly_snail_isola...,endosymbiont_of_unidentified_scaly_snail_isola...,12
51233,PC834369,9,0.814424,4.073355e-33,8.114139e-24,4.929791e-27,6.959541e-29,1.641622e-13,3.586351e-20,4.193244e-13,...,62322,NODE_19_length_108853_cov_56.394312,283,35,6814,Otu1225,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,MC4_S2_contigs.kf,MC4_S2_contigs,10

In [73]:
len(my_subset)/len(classes_df_merged)

0.03417252146760343

In [74]:
my_subset = classes_df_merged.loc[(classes_df_merged['top_p'] > 0.9)]
len(my_subset)

49874

In [75]:
classes_df_merged.columns

Index(['genome_x', 'top_class', 'top_p', 'clade_0', 'clade_1', 'clade_2',
       'clade_3', 'clade_4', 'clade_5', 'clade_6', 'clade_7', 'clade_8',
       'clade_9', 'clade_10', 'clade_11', 'clade_12', 'clade_13', 'clade_14',
       'clade_15', 'label', '#anonymous_contig_id', 'genome_id', 'tax_id',
       'contig_id', 'number_reads', 'start_position', 'end_position', 'otu',
       'full_path', 'path', 'new_label', 'true_clade'],
      dtype='object')

In [76]:
classes_df_merged

,genome_x,top_class,top_p,clade_0,clade_1,clade_2,clade_3,clade_4,clade_5,clade_6,...,tax_id,contig_id,number_reads,start_position,end_position,otu,full_path,path,new_label,true_clade
0,PC96897,13,1.000000,2.828151e-23,1.300274e-27,1.909033e-26,2.160892e-19,2.009723e-32,1.816115e-13,4.087004e-26,...,1453352,CP010535.1,214,1326961,1332977,Otu1168.0,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Sediminicola_sp_YIK13_genomic.kf,Sediminicola_sp_YIK13_genomic,13
1,PC988428,10,1.000000,3.696906e-41,4.672891e-24,1.703767e-28,6.741611e-29,1.057825e-27,3.044746e-32,4.802668e-23,...,80852,NODE_76_length_18850_cov_92.515569,276,8186,16309,Otu1132,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,VwK7F1_S12_contigs.kf,VwK7F1_S12_contigs,10
2,PC988212,10,1.000000,0.000000e+00,1.509885e-40,0.000000e+00,0.000000e+00,1.401298e-45,6.566050e-37,1.321604e-39,...,62322,NODE_39_length_27622_cov_43.324168,635,13834,27609,Otu1225,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,MC4_S2_contigs.kf,MC4_S2_contigs,10
3,PC976607,4,1.000000,8.856206e-43,1.994640e-38,1.473306e-36,6.351124e-32,1.000000e+00,1.537777e-19,1.128529e-29,...,1760,NODE_4_length_310521_cov_112.470128,236,85326,93472,Otu812,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Titti28_S8_contigs.kf,Titti28_S8_contigs,4
4,PC956737,13,1.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.401298e-45,0.000000e+00,7.496947e-43,...,979,CP002534.1,276,1299315,1308746,Otu612.0,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Cellulophaga_lytica_DSM_7489_genomic.kf,Cellulophaga_lytica_DSM_7489_genomic,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51235,PC835777,3,0.999999,2.651828e-32,1.700928e-22,1.429786e-06,9.999986e-01,3.464907e-14,7.073279e-14,2.112509e-28,...,1763538,NZ_CP017770.1,402,3085501,3095245,Otu722,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Paenibacillus_sp_LPB0068_genomic.kf,Paenibacillus_sp_LPB0068_genomic,3
51236,PC866532,13,1.000000,4.804060e-16,6.967587e-15,4.165061e-23,1.023033e-12,1.776413e-23,8.070257e-28,1.825344e-22,...,237,NODE_14_length_85852_cov_79.949699,1702,54953,85835,Otu491.0,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,26_S2_contigs.kf,26_S2_contigs,13
51237,PC843714,13,0.999929,1.506772e-22,1.173792e-23,6.527935e-12,6.416671e-20,9.273941e-20,3.571406e-14,8.598757e-25,...,313603,CP002157.1,218,3718871,3726221,Otu1267.0,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Maribacter_sp_HTCC2170_genomic.kf,Maribacter_sp_HTCC2170_genomic,13
51238,PC863748,10,0.991869,1.387357e-30,2.260021e-12,2.470852e-24,1.282304e-20,2.666388e-14,3.668712e-12,1.422128e-14,...,22,CP000444.1,264,2647833,2657745,Otu2333,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,Shewanella_sp_MR-7_genomic.kf,Shewanella_sp_MR-7_genomic,10
51239,PC897370,11,1.000000,6.594735e-40,1.808196e-32,1.851686e-30,1.052898e-33,9.733682e-16,3.568218e-11,8.961638e-19,...,32644,0RNODE_248_length_5318_cov_4.74604,776,13,5294,RNODE_248_length_5318_cov_4.74604,/net/sgi/cami/data/CAMI2/nwillassen_data/marin...,RNODE_248_length_5318_cov_4.74604.kf,RNODE_248_length_5318_cov_4.74604,11

In [77]:

len_p = "/Users/nora/Documents/ml_metagenomics/tol_variable_k_resuls/cami_gsa_pooled/cami_short_reads_gsa_pooled_5kfilt_contigs"

col_names = ["genome_x", "length", "A", "C", "G", "T", "2", "3", "4", "CpG", "tv", "ts", "CpG-ts"]

length_df = pd.read_csv(os.path.join(len_p, "cami_short_reads_gsa_5K_contigs_LENGTH.txt"), sep = "\t", header = None, names = col_names)

In [78]:
length_df

,genome_x,length,A,C,G,T,2,3,4,CpG,tv,ts,CpG-ts
0,PC1000033,12468,3768,2278,1988,4434,0,0,0,620,0,0,0
1,PC1000034,26531,7219,6735,5727,6850,0,0,0,2698,0,0,0
2,PC1000073,7064,2079,1453,1353,2179,0,0,0,412,0,0,0
3,PC1000081,7389,2095,1424,1589,2281,0,0,0,602,0,0,0
4,PC1000092,5778,1399,1373,1530,1476,0,0,0,756,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
51235,PC999876,12618,4236,1917,2124,4341,0,0,0,478,0,0,0
51236,PC999887,24012,6923,5262,4118,7709,0,0,0,1556,0,0,0
51237,PC999921,7758,2063,1716,1964,2015,0,0,0,1082,0,0,0
51238,PC99996,7410,1885,1485,1862,2178,0,0,0,772,0,0,0
51239,PC999974,8067,2166,1709,1776,2416,0,0,0,594,0,0,0

In [79]:
classes_df_merged_2 = pd.merge(classes_df_merged, length_df, how = "left", left_on = "genome_x", right_on = "genome_x" )

In [80]:
classes_df_merged_2

,genome_x,top_class,top_p,clade_0,clade_1,clade_2,clade_3,clade_4,clade_5,clade_6,...,C,G,T,2,3,4,CpG,tv,ts,CpG-ts
0,PC96897,13,1.000000,2.828151e-23,1.300274e-27,1.909033e-26,2.160892e-19,2.009723e-32,1.816115e-13,4.087004e-26,...,1093,1358,1582,0,0,0,338,0,0,0
1,PC988428,10,1.000000,3.696906e-41,4.672891e-24,1.703767e-28,6.741611e-29,1.057825e-27,3.044746e-32,4.802668e-23,...,1522,1607,2603,0,0,0,558,0,0,0
2,PC988212,10,1.000000,0.000000e+00,1.509885e-40,0.000000e+00,0.000000e+00,1.401298e-45,6.566050e-37,1.321604e-39,...,3434,3131,3785,0,0,0,1600,0,0,0
3,PC976607,4,1.000000,8.856206e-43,1.994640e-38,1.473306e-36,6.351124e-32,1.000000e+00,1.537777e-19,1.128529e-29,...,2765,2892,1264,0,0,0,2508,0,0,0
4,PC956737,13,1.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.401298e-45,0.000000e+00,7.496947e-43,...,1744,1259,3379,0,0,0,252,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51235,PC835777,3,0.999999,2.651828e-32,1.700928e-22,1.429786e-06,9.999986e-01,3.464907e-14,7.073279e-14,2.112509e-28,...,1715,2365,2612,0,0,0,808,0,0,0
51236,PC866532,13,1.000000,4.804060e-16,6.967587e-15,4.165061e-23,1.023033e-12,1.776413e-23,8.070257e-28,1.825344e-22,...,5617,4283,10752,0,0,0,1234,0,0,0
51237,PC843714,13,0.999929,1.506772e-22,1.173792e-23,6.527935e-12,6.416671e-20,9.273941e-20,3.571406e-14,8.598757e-25,...,1410,1331,2221,0,0,0,424,0,0,0
51238,PC863748,10,0.991869,1.387357e-30,2.260021e-12,2.470852e-24,1.282304e-20,2.666388e-14,3.668712e-12,1.422128e-14,...,2363,2156,2614,0,0,0,1004,0,0,0
51239,PC897370,11,1.000000,6.594735e-40,1.808196e-32,1.851686e-30,1.052898e-33,9.733682e-16,3.568218e-11,8.961638e-19,...,1575,1646,1016,0,0,0,1094,0,0,0

In [81]:
classes_df_merged_2["length_adj"] = classes_df_merged_2["A"] + classes_df_merged_2["C"] + classes_df_merged_2["G"] + classes_df_merged_2["T"]

In [82]:
classes_df_merged_2

,genome_x,top_class,top_p,clade_0,clade_1,clade_2,clade_3,clade_4,clade_5,clade_6,...,G,T,2,3,4,CpG,tv,ts,CpG-ts,length_adj
0,PC96897,13,1.000000,2.828151e-23,1.300274e-27,1.909033e-26,2.160892e-19,2.009723e-32,1.816115e-13,4.087004e-26,...,1358,1582,0,0,0,338,0,0,0,6017
1,PC988428,10,1.000000,3.696906e-41,4.672891e-24,1.703767e-28,6.741611e-29,1.057825e-27,3.044746e-32,4.802668e-23,...,1607,2603,0,0,0,558,0,0,0,8124
2,PC988212,10,1.000000,0.000000e+00,1.509885e-40,0.000000e+00,0.000000e+00,1.401298e-45,6.566050e-37,1.321604e-39,...,3131,3785,0,0,0,1600,0,0,0,13776
3,PC976607,4,1.000000,8.856206e-43,1.994640e-38,1.473306e-36,6.351124e-32,1.000000e+00,1.537777e-19,1.128529e-29,...,2892,1264,0,0,0,2508,0,0,0,8147
4,PC956737,13,1.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.401298e-45,0.000000e+00,7.496947e-43,...,1259,3379,0,0,0,252,0,0,0,9432
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51235,PC835777,3,0.999999,2.651828e-32,1.700928e-22,1.429786e-06,9.999986e-01,3.464907e-14,7.073279e-14,2.112509e-28,...,2365,2612,0,0,0,808,0,0,0,9745
51236,PC866532,13,1.000000,4.804060e-16,6.967587e-15,4.165061e-23,1.023033e-12,1.776413e-23,8.070257e-28,1.825344e-22,...,4283,10752,0,0,0,1234,0,0,0,30883
51237,PC843714,13,0.999929,1.506772e-22,1.173792e-23,6.527935e-12,6.416671e-20,9.273941e-20,3.571406e-14,8.598757e-25,...,1331,2221,0,0,0,424,0,0,0,7351
51238,PC863748,10,0.991869,1.387357e-30,2.260021e-12,2.470852e-24,1.282304e-20,2.666388e-14,3.668712e-12,1.422128e-14,...,2156,2614,0,0,0,1004,0,0,0,9913
51239,PC897370,11,1.000000,6.594735e-40,1.808196e-32,1.851686e-30,1.052898e-33,9.733682e-16,3.568218e-11,8.961638e-19,...,1646,1016,0,0,0,1094,0,0,0,5282

In [95]:
len(classes_df_merged_2.columns)

45

In [83]:
pl_f = "cami_gsa_short_reads_all.pl_err"
placement_df = pd.read_csv(os.path.join(classes_p, pl_f), sep = " ", header = None, names = ["genome_x", "a", "pl_err", "b"])

In [84]:
# Remove extra rows
placement_df = placement_df[~(placement_df['pl_err'].isna())]

# Remove NAN columns
placement_df.dropna(axis=1, how='all', inplace = True)

In [85]:
placement_df.index.names = ["genome_x"]
placement_df.reset_index(inplace=True)


# Reformat genome name
placement_df['genome_x'] = placement_df['genome_x'].str.replace('apples_input_di_mtrx_query_','')
placement_df['genome_x'] = placement_df['genome_x'].str.replace('.pl_err','')

In [86]:
placement_df

       genome_x      a  pl_err       b
0      PC950929  50751       0  0.0000
1      PC951019  50751       3  0.0001
2      PC951080  50751       0  0.0000
3      PC951211  50751       3  0.0001
4      PC951233  50751       5  0.0001
...         ...    ...     ...     ...
51235  PC950849  50751       1  0.0000
51236  PC950865  50751       1  0.0000
51237  PC950880  50751       5  0.0001
51238   PC95089  50751       0  0.0000
51239  PC950916  50751      16  0.0003

[51240 rows x 4 columns]

In [87]:
df_summary = pd.merge(placement_df, classes_df_merged_2, how = 'left', left_on = "genome_x", right_on = "genome_x")

In [88]:
df_summary

,genome_x,a,pl_err,b,top_class,top_p,clade_0,clade_1,clade_2,clade_3,...,G,T,2,3,4,CpG,tv,ts,CpG-ts,length_adj
0,PC950929,50751,0,0.0000,11,1.000000,0.000000e+00,0.000000e+00,8.523258e-41,1.600881e-38,...,8824,5478,0,0,0,5876,0,0,0,25858
1,PC951019,50751,3,0.0001,10,1.000000,2.594882e-40,3.033828e-30,5.295705e-24,2.237660e-31,...,1337,1950,0,0,0,492,0,0,0,6647
2,PC951080,50751,0,0.0000,15,1.000000,0.000000e+00,0.000000e+00,0.000000e+00,5.071404e-25,...,5870,7042,0,0,0,2514,0,0,0,25708
3,PC951211,50751,3,0.0001,12,0.999807,1.233214e-06,6.448637e-11,1.197054e-21,1.860200e-07,...,1992,4323,0,0,0,302,0,0,0,12124
4,PC951233,50751,5,0.0001,14,1.000000,1.242491e-28,1.089975e-31,5.763922e-21,2.568561e-19,...,1244,3237,0,0,0,296,0,0,0,9249
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51235,PC950849,50751,1,0.0000,10,0.989682,4.579189e-16,3.873176e-04,5.643870e-11,9.917255e-03,...,1808,1375,0,0,0,1092,0,0,0,6239
51236,PC950865,50751,1,0.0000,11,1.000000,0.000000e+00,4.203895e-45,0.000000e+00,2.569456e-39,...,1794,1019,0,0,0,1248,0,0,0,5363
51237,PC950880,50751,5,0.0001,10,0.999586,4.852986e-29,1.933796e-06,1.032244e-14,1.946849e-19,...,1658,2529,0,0,0,656,0,0,0,8177
51238,PC95089,50751,0,0.0000,11,1.000000,0.000000e+00,4.511340e-41,2.063178e-29,3.285302e-34,...,3456,2177,0,0,0,2470,0,0,0,11150
51239,PC950916,50751,16,0.0003,2,1.000000,1.829884e-29,7.705683e-22,1.000000e+00,1.490679e-14,...,1184,1611,0,0,0,788,0,0,0,5894

In [93]:
df_summary["model"] = "TOL_65K_ChunkExp"
len(df_summary)

51240

In [92]:
df_summary2=df_summary.dropna()
len(df_summary2)

51240

In [91]:
df_summary2.to_csv(os.path.join(os.getcwd(), "summary_cami_short_reads_gsa_65KTOL_ChunkExp.pl_error"), index=False, sep=' ', header=True)

In [203]:
df_summary2[df_summary2.isnull().any(axis=1)]

Empty DataFrame
Columns: [genome_x, a, pl_err, b, top_class, top_p, clade_0, clade_1, clade_2, clade_3, clade_4, clade_5, clade_6, clade_7, clade_8, clade_9, clade_10, clade_11, clade_12, clade_13, clade_14, clade_15, label, #anonymous_contig_id, genome_id, tax_id, contig_id, number_reads, start_position, end_position, otu, full_path, path, new_label, true_clade, length, A, C, G, T, 2, 3, 4, CpG, tv, ts, CpG-ts, length_adj, model]
Index: []

[0 rows x 49 columns]

In [127]:
des = df_summary.groupby("parent_genome").describe()
#des = df_summary.groupby(["parent_genome"])['pl_err', ].mean()

In [129]:
des.reset_index(inplace=True)

In [130]:
des

    parent_genome      a                                                    \
                   count     mean  std      min      25%      50%      75%
0      G000006865  176.0  10069.0  0.0  10069.0  10069.0  10069.0  10069.0
1      G000006925  373.0  10069.0  0.0  10069.0  10069.0  10069.0  10069.0
2      G000007385  359.0  10069.0  0.0  10069.0  10069.0  10069.0  10069.0
3      G000007705  356.0  10069.0  0.0  10069.0  10069.0  10069.0  10069.0
4      G000007845  395.0  10069.0  0.0  10069.0  10069.0  10069.0  10069.0
..            ...    ...      ...  ...      ...      ...      ...      ...
495    G900129715  286.0  10069.0  0.0  10069.0  10069.0  10069.0  10069.0
496    G900129805  159.0  10069.0  0.0  10069.0  10069.0  10069.0  10069.0
497    G900129845  243.0  10069.0  0.0  10069.0  10069.0  10069.0  10069.0
498    G900130035  245.0  10069.0  0.0  10069.0  10069.0  10069.0  10069.0
499    G900142495  281.0  10069.0  0.0  10069.0  10069.0  10069.0  10069.0

             pl_err  ... CpG-ts      length_adj                             \
         max  count  ...    75%  max      count          mean          std
0    10069.0  176.0  ...    0.0  0.0      176.0  12126.482955  7034.067522
1    10069.0  373.0  ...    0.0  0.0      373.0  11567.900804  6173.670073
2    10069.0  359.0  ...    0.0  0.0      359.0  12126.715877  6417.875431
3    10069.0  356.0  ...    0.0  0.0      356.0  12206.918539  6952.165247
4    10069.0  395.0  ...    0.0  0.0      395.0  12110.670886  6767.358949
..       ...    ...  ...    ...  ...        ...           ...          ...
495  10069.0  286.0  ...    0.0  0.0      286.0  11353.080420  5873.325069
496  10069.0  159.0  ...    0.0  0.0      159.0  11198.836478  5756.736091
497  10069.0  243.0  ...    0.0  0.0      243.0  11743.234568  6443.362254
498  10069.0  245.0  ...    0.0  0.0      245.0  11630.297959  6379.070461
499  10069.0  281.0  ...    0.0  0.0      281.0  11675.234875  6391.916673


        min      25%      50%       75%      max
0    5084.0  7095.50  10439.0  14213.00  45955.0
1    5063.0  6829.00   9654.0  15071.00  45955.0
2    5134.0  7345.50   9982.0  15269.00  45955.0
3    5007.0  7067.50  10331.0  15625.75  45955.0
4    5007.0  7097.00  10144.0  15610.50  45955.0
..      ...      ...      ...       ...      ...
495  5020.0  6961.75   9832.0  13339.25  41230.0
496  5094.0  6943.00   9644.0  13361.50  44811.0
497  5007.0  7154.50   9651.0  14759.50  41073.0
498  5012.0  7021.00  10044.0  13921.00  45955.0
499  5009.0  7301.00   9845.0  13996.00  48816.0

[500 rows x 145 columns]

In [131]:
des.columns.to_list()

[('parent_genome', ''),
 ('a', 'count'),
 ('a', 'mean'),
 ('a', 'std'),
 ('a', 'min'),
 ('a', '25%'),
 ('a', '50%'),
 ('a', '75%'),
 ('a', 'max'),
 ('pl_err', 'count'),
 ('pl_err', 'mean'),
 ('pl_err', 'std'),
 ('pl_err', 'min'),
 ('pl_err', '25%'),
 ('pl_err', '50%'),
 ('pl_err', '75%'),
 ('pl_err', 'max'),
 ('b', 'count'),
 ('b', 'mean'),
 ('b', 'std'),
 ('b', 'min'),
 ('b', '25%'),
 ('b', '50%'),
 ('b', '75%'),
 ('b', 'max'),
 ('top_class', 'count'),
 ('top_class', 'mean'),
 ('top_class', 'std'),
 ('top_class', 'min'),
 ('top_class', '25%'),
 ('top_class', '50%'),
 ('top_class', '75%'),
 ('top_class', 'max'),
 ('true_clade', 'count'),
 ('true_clade', 'mean'),
 ('true_clade', 'std'),
 ('true_clade', 'min'),
 ('true_clade', '25%'),
 ('true_clade', '50%'),
 ('true_clade', '75%'),
 ('true_clade', 'max'),
 ('length', 'count'),
 ('length', 'mean'),
 ('length', 'std'),
 ('length', 'min'),
 ('length', '25%'),
 ('length', '50%'),
 ('length', '75%'),
 ('length', 'max'),
 ('A', 'count'),
 ('A', 'mean'),
 ('A', 'std'),
 ('A', 'min'),
 ('A', '25%'),
 ('A', '50%'),
 ('A', '75%'),
 ('A', 'max'),
 ('C', 'count'),
 ('C', 'mean'),
 ('C', 'std'),
 ('C', 'min'),
 ('C', '25%'),
 ('C', '50%'),
 ('C', '75%'),
 ('C', 'max'),
 ('G', 'count'),
 ('G', 'mean'),
 ('G', 'std'),
 ('G', 'min'),
 ('G', '25%'),
 ('G', '50%'),
 ('G', '75%'),
 ('G', 'max'),
 ('T', 'count'),
 ('T', 'mean'),
 ('T', 'std'),
 ('T', 'min'),
 ('T', '25%'),
 ('T', '50%'),
 ('T', '75%'),
 ('T', 'max'),
 ('2', 'count'),
 ('2', 'mean'),
 ('2', 'std'),
 ('2', 'min'),
 ('2', '25%'),
 ('2', '50%'),
 ('2', '75%'),
 ('2', 'max'),
 ('3', 'count'),
 ('3', 'mean'),
 ('3', 'std'),
 ('3', 'min'),
 ('3', '25%'),
 ('3', '50%'),
 ('3', '75%'),
 ('3', 'max'),
 ('4', 'count'),
 ('4', 'mean'),
 ('4', 'std'),
 ('4', 'min'),
 ('4', '25%'),
 ('4', '50%'),
 ('4', '75%'),
 ('4', 'max'),
 ('CpG', 'count'),
 ('CpG', 'mean'),
 ('CpG', 'std'),
 ('CpG', 'min'),
 ('CpG', '25%'),
 ('CpG', '50%'),
 ('CpG', '75%'),
 ('CpG', 'max'),
 ('tv', 'count'),
 ('tv', 'mean'),
 ('tv', 'std'),
 ('tv', 'min'),
 ('tv', '25%'),
 ('tv', '50%'),
 ('tv', '75%'),
 ('tv', 'max'),
 ('ts', 'count'),
 ('ts', 'mean'),
 ('ts', 'std'),
 ('ts', 'min'),
 ('ts', '25%'),
 ('ts', '50%'),
 ('ts', '75%'),
 ('ts', 'max'),
 ('CpG-ts', 'count'),
 ('CpG-ts', 'mean'),
 ('CpG-ts', 'std'),
 ('CpG-ts', 'min'),
 ('CpG-ts', '25%'),
 ('CpG-ts', '50%'),
 ('CpG-ts', '75%'),
 ('CpG-ts', 'max'),
 ('length_adj', 'count'),
 ('length_adj', 'mean'),
 ('length_adj', 'std'),
 ('length_adj', 'min'),
 ('length_adj', '25%'),
 ('length_adj', '50%'),
 ('length_adj', '75%'),
 ('length_adj', 'max')]

In [132]:
des['pl_err', 'mean']

0      14.829545
1      20.402145
2      12.395543
3      18.258427
4      13.336709
         ...
495    14.479021
496     7.289308
497    12.790123
498     5.848980
499     9.014235
Name: (pl_err, mean), Length: 500, dtype: float64

In [133]:
final_table_columns = [('parent_genome',      ''), ('pl_err', 'mean'), ('pl_err', 'count')]
des2 = des.drop(columns=[col for col in des if col not in final_table_columns])

In [134]:
des2

    parent_genome pl_err
                   count       mean
0      G000006865  176.0  14.829545
1      G000006925  373.0  20.402145
2      G000007385  359.0  12.395543
3      G000007705  356.0  18.258427
4      G000007845  395.0  13.336709
..            ...    ...        ...
495    G900129715  286.0  14.479021
496    G900129805  159.0   7.289308
497    G900129845  243.0  12.790123
498    G900130035  245.0   5.848980
499    G900142495  281.0   9.014235

[500 rows x 3 columns]